@extends('layouts.app')
@section('top_title','Admin Dashboard')
@section('content')
<div class="hero-card"><div class="hero-kicker">Vaccination operations</div><div class="hero-title">Good day, {{auth()->user()->name}}</div><div class="hero-text">Monitor children, vaccine availability, hospital activity and appointment requests from one centralized workspace.</div></div>
<div class="grid stats-grid">
@foreach([['parents','Registered Parents','bi-people-fill'],['children','Total Children','bi-person-hearts'],['hospitals','Partner Hospitals','bi-hospital-fill'],['pending','Pending Requests','bi-hourglass-split'],['vaccinations','Vaccination Records','bi-shield-check']] as $s)
<div class="stat-card"><div><div class="stat-label">{{$s[1]}}</div><div class="stat-value">{{$stats[$s[0]]}}</div></div><div class="stat-icon"><i class="bi {{$s[2]}}"></i></div></div>
@endforeach
</div>
<div class="grid dashboard-grid">
<section class="table-card"><div class="panel-head"><div><div class="panel-title">Upcoming appointments</div><div class="muted" style="font-size:11px;margin-top:3px">Next scheduled vaccination visits</div></div><a class="btn btn-light" href="{{route('admin.bookings')}}">View all</a></div><div class="table-wrap"><table class="table"><thead><tr><th>Child</th><th>Vaccine</th><th>Hospital</th><th>Schedule</th><th>Status</th></tr></thead><tbody>@forelse($upcoming as $a)<tr><td><div class="person"><span class="avatar">{{strtoupper(substr($a->child->name,0,1))}}</span>{{$a->child->name}}</div></td><td>{{$a->vaccine->name}}</td><td>{{$a->hospital->name}}</td><td>{{$a->appointment_date->format('d M Y')}}<br><span class="muted">{{$a->appointment_time}}</span></td><td><span class="badge {{in_array($a->status,['Approved','Completed'])?'badge-success':($a->status==='Pending'?'badge-warning':'badge-danger')}}">{{$a->status}}</span></td></tr>@empty<tr><td colspan="5"><div class="empty">No upcoming appointments.</div></td></tr>@endforelse</tbody></table></div></section>
<section class="panel"><div class="panel-head"><div><div class="panel-title">Vaccination activity</div><div class="muted" style="font-size:11px">Operational overview</div></div></div><div class="panel-body"><div class="metric-row"><div class="mini-metric"><div class="value">{{$stats['vaccinations']}}</div><div class="label">Records</div></div><div class="mini-metric"><div class="value">{{$stats['pending']}}</div><div class="label">Pending</div></div><div class="mini-metric"><div class="value">{{$stats['hospitals']}}</div><div class="label">Hospitals</div></div></div><div style="margin-top:22px"><div style="display:flex;justify-content:space-between;font-size:11px;font-weight:750;margin-bottom:7px"><span>System activity</span><span>Healthy</span></div><div class="progress"><span style="width:86%"></span></div></div><div style="margin-top:22px;display:grid;gap:10px"><a class="btn btn-light" style="justify-content:flex-start" href="{{route('admin.bookings')}}"><i class="bi bi-calendar-check"></i> Review appointment requests</a><a class="btn btn-light" style="justify-content:flex-start" href="{{route('admin.vaccines')}}"><i class="bi bi-capsule-pill"></i> Manage vaccine catalogue</a><a class="btn btn-light" style="justify-content:flex-start" href="{{route('admin.reports')}}"><i class="bi bi-bar-chart"></i> Open reports</a></div></div></section>
</div>
@endsection
