<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="csrf-token" content="{{ csrf_token() }}"><title>@yield('title','VaccineCare')</title><link rel="stylesheet" href="{{ asset('css/app.css') }}"><link rel="preconnect" href="https://fonts.googleapis.com"><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin><link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700;800&display=swap" rel="stylesheet"><link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css"></head><body>@auth
<div class="app-shell"><aside class="sidebar"><a class="brand" href="{{ route('dashboard') }}"><span class="brand-mark"><i class="bi bi-heart-pulse-fill"></i></span><span><span class="brand-title">VaccineCare</span><span class="brand-sub">Vaccination Management</span></span></a>
@php($role=auth()->user()->role)
<div class="nav-label">Workspace</div>
<a class="side-link {{ request()->routeIs($role.'.dashboard') ? 'active':'' }}" href="{{ route($role.'.dashboard') }}"><i class="bi bi-grid-1x2-fill"></i> Dashboard</a>
@if($role==='admin')
<a class="side-link {{ request()->routeIs('admin.children')?'active':'' }}" href="{{route('admin.children')}}"><i class="bi bi-people-fill"></i> Children</a><a class="side-link {{ request()->routeIs('admin.vaccines')?'active':'' }}" href="{{route('admin.vaccines')}}"><i class="bi bi-capsule-pill"></i> Vaccines</a><a class="side-link {{ request()->routeIs('admin.hospitals')?'active':'' }}" href="{{route('admin.hospitals')}}"><i class="bi bi-hospital-fill"></i> Hospitals</a><a class="side-link {{ request()->routeIs('admin.bookings')?'active':'' }}" href="{{route('admin.bookings')}}"><i class="bi bi-calendar2-check-fill"></i> Appointments</a><a class="side-link {{ request()->routeIs('admin.reports')?'active':'' }}" href="{{route('admin.reports')}}"><i class="bi bi-bar-chart-fill"></i> Reports</a>
@elseif($role==='parent')
<a class="side-link {{ request()->routeIs('parent.children')?'active':'' }}" href="{{route('parent.children')}}"><i class="bi bi-person-hearts"></i> My Children</a><a class="side-link {{ request()->routeIs('parent.hospitals')?'active':'' }}" href="{{route('parent.hospitals')}}"><i class="bi bi-search"></i> Find Hospital</a><a class="side-link {{ request()->routeIs('parent.appointments')?'active':'' }}" href="{{route('parent.appointments')}}"><i class="bi bi-calendar-check"></i> Appointments</a><a class="side-link {{ request()->routeIs('parent.records')?'active':'' }}" href="{{route('parent.records')}}"><i class="bi bi-file-medical-fill"></i> Vaccination Records</a><a class="side-link {{ request()->routeIs('parent.profile')?'active':'' }}" href="{{route('parent.profile')}}"><i class="bi bi-person-circle"></i> My Profile</a>
@else
<a class="side-link {{ request()->routeIs('hospital.appointments')?'active':'' }}" href="{{route('hospital.appointments')}}"><i class="bi bi-calendar2-week-fill"></i> Appointments</a><a class="side-link {{ request()->routeIs('hospital.profile')?'active':'' }}" href="{{route('hospital.profile')}}"><i class="bi bi-building"></i> Hospital Profile</a>
@endif
<div class="sidebar-footer"><div class="muted" style="font-size:11px;margin-bottom:9px">SIGNED IN AS</div><div style="font-size:13px;color:#fff;font-weight:700">{{auth()->user()->name}}</div><div style="font-size:11px;color:#64748b;margin-top:3px">{{ucfirst($role)}} account</div></div></aside><div class="mobile-overlay"></div><div class="main"><header class="topbar"><div style="display:flex;align-items:center;gap:12px"><button class="btn btn-light mobile-menu" data-menu><i class="bi bi-list"></i></button><div><div class="top-title">@yield('top_title','Dashboard')</div><div class="top-meta">{{ now()->format('l, d M Y') }}</div></div></div><div class="profile-chip"><span class="profile-dot">{{strtoupper(substr(auth()->user()->name,0,1))}}</span><div style="display:none" class="top-meta">{{auth()->user()->email}}</div><form method="POST" action="{{route('logout')}}">@csrf<button class="btn btn-light" type="submit"><i class="bi bi-box-arrow-right"></i> Logout</button></form></div></header><main class="content">@if(session('success'))<div class="flash flash-success"><i class="bi bi-check-circle-fill"></i> {{session('success')}}</div>@endif @if($errors->any())<div class="flash flash-error"><i class="bi bi-exclamation-triangle-fill"></i> {{$errors->first()}}</div>@endif @yield('content')</main></div></div>
@else @yield('guest_content') @endauth<script src="{{asset('js/app.js')}}"></script></body></html>
